### ISSUE TITLE
Can't open trading position.

### ISSUE THREAD

**Issue by OrzPond** [m-root/primebit-api-sdk#1]
Working fine when get an account detail but unauthorized when open trading position.

It's show

<Response [401]>
{'error': {'code': 'unauthorized', 'message': 'Unauthorized'}}

**Comment by m-root** [comment]
> Working fine when get an account detail but unauthorized when open trading position.
> 
> It's show
> 
> <Response [401]>
> {'error': {'code': 'unauthorized', 'message': 'Unauthorized'}}

First of all, pay what you owe me!!!

**Comment by OrzPond** [comment]
> 
> 
> > Working fine when get an account detail but unauthorized when open trading position.
> > It's show
> > <Response [401]>
> > {'error': {'code': 'unauthorized', 'message': 'Unauthorized'}}
> 
> First of all, pay what you owe me!!!

I'm think this guy is cheating you not me? 
Cause I pay for this guy from freelancer for this project.

He tell me his friend(you) will help this project, I'm sure you're a man who remote to my computer.
I'm so sorry and I don't know he cheat you.

https://www.freelancer.com/projects/python/Python-API-wrapper-for-Primebit-24822759/proposals

**Comment by OrzPond** [comment]
Hello and sorry the guy I pay for this project(Bhoodev P.) not reply my question about this scam.
I love your Primebit project. Tell me if you have a way to contact me in private. 
I don't know what this project price Bhoodev P. will pay you but I think I can pay you.

**Comment by m-root** [comment]
If you feel like you need my help, you do know my Skype ID, so ping me there. You had gladly hosted the project on your time git and did delete it.

**Comment by OrzPond** [comment]
Sorry but I'm don't used Skype. I'm don't know your contact you.
I'm only find you when I'm search Primebit api in github.

**Comment by m-root** [comment]
Apr 13, 2020 - Apr 19, 2020 | 1 day, 5 hours | Payment Failed | $2,062.48 USD |

**Comment by OrzPond** [comment]
Sorry but $2,062.48 is to much for me to pay.

**Comment by m-root** [comment]
What are you able to pay?

**Comment by OrzPond** [comment]
Sorry but my max is $500. You know my budget from my link when I'm find freelance for this job.

**Comment by m-root** [comment]
Send the amount via BTC

**Comment by OrzPond** [comment]
send you contact to sup.pond@gmail.com

**Comment by OrzPond** [comment]
And can you capture chat and detail you talk with Bhoodev P.  to me please.
I'm want to know he use my name or my face when he talk to you.
